RISK_THRESHOLD_NORMAL = 0.26
RISK_THRESHOLD_WARNING = 0.45
RISK_THRESHOLD_CRITICAL = 0.65

HEALTH_SCORE_DECIMALS = 2

HEALTH_LEVEL_NORMAL = "normal"
HEALTH_LEVEL_ATTENTION = "attention"
HEALTH_LEVEL_WARNING = "warning"
HEALTH_LEVEL_CRITICAL = "critical"

HEALTH_STATUS_NORMAL = "正常"
HEALTH_STATUS_ATTENTION = "关注"
HEALTH_STATUS_WARNING = "预警"
HEALTH_STATUS_CRITICAL = "严重"

HEALTH_DESCRIPTION_NORMAL = "设备当前风险较低，运行状态正常"
HEALTH_DESCRIPTION_ATTENTION = "设备风险开始升高，建议持续关注"
HEALTH_DESCRIPTION_WARNING = "设备健康状态下降，建议重点检查"
HEALTH_DESCRIPTION_CRITICAL = "设备处于高风险状态，建议及时处理"

ALERT_LEVEL_NONE = "none"
ALERT_LEVEL_LOW = "low"
ALERT_LEVEL_MEDIUM = "medium"
ALERT_LEVEL_HIGH = "high"

ALERT_STATUS_NONE = "none"
ALERT_STATUS_UNHANDLED = "unhandled"

ALERT_STATUS_TEXT_NONE = "无"
ALERT_STATUS_TEXT_UNHANDLED = "未处理"

ALERT_MESSAGE_NONE = "当前设备状态正常，暂未生成告警"
ALERT_MESSAGE_LOW = "设备风险开始升高，建议关注"
ALERT_MESSAGE_MEDIUM = "设备存在异常风险，建议检查"
ALERT_MESSAGE_HIGH = "设备处于高风险状态，请及时处理"

ALERT_ADVICE_NONE = "保持常规监测"
ALERT_ADVICE_LOW = "建议持续观察设备风险变化趋势"
ALERT_ADVICE_MEDIUM = "建议结合历史数据和运行状态进行排查"
ALERT_ADVICE_HIGH = "建议及时安排检修或重点复核"
